name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Update the ToC in the README.md
        run: npx markdown-toc README.md -i

      - name: Build app
        run: npm run build

      - name: Semantic release
        uses: codfish/semantic-release-action@v3
        id: semanticrelease
        with:
          additional-packages: |
            ['@semantic-release/git', '@semantic-release/changelog']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create archive
        run: /usr/bin/7za a app.7z ./out/* ./package.json ./captain.md ./CHANGELOG.md

      - name: Add archive to release
        uses: softprops/action-gh-release@v1
        with:
          files: app.7z
          tag_name: $RELEASE_GIT_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
